name: terminui_example
description: "Example of using the terminui package"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  terminui:
    path: ../

dev_dependencies:
  flame_lint: ^1.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
