name: terminui
description: "An extensible and customizable terminal like view to be interacted with commands."
version: 0.2.0
homepage: https://github.com/erickzanardo/terminui

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  args: ^2.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.2.1
  flutter_test:
    sdk: flutter
